### ISSUE TITLE
Official pages

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#10]
## Objective

Provide more legal info to website users.

> It's all about to typical website pages like Abuse, Terms of use, Disclaimer etc.
## Problem

There is no information like who we (GDG) are or what are the terms of use of the regform. There is also no disclaimer, that GDG cannot be related to Google Inc. We have to provide that information on the website.
## TODO

As there is no actual text (@webknjaz, please request that pages content) right now, the only thing can be done is to create handlers for all required pages, which return templates with no text or dummy text on them. Consult to @webknjaz about how it should be implemented (class-based view, or just endpoint functions).
It is also required to provide opengraph metatags in that templates. Look [here](https://github.com/GDG-Ukraine/gdg.org.ua/blob/api-for-admin/src/GDGUkraine/templates/event.html#L13-L28) on how they are added on another page.
- [ ] Create `default()` handler in root controller looking for templates in specific directory and raising `HTTPError()` in case of failure
- [ ] Make some basic template for pages with blocks (like title and content), so it could be inherited, make sure it doesn't get rendered itself (put it into upper dir). Don't commit inherited pages at this point (see below)
- [ ] Make common footer and add it to all pages, so it would be easy to add page links there
- [ ] Wait until we post some texts for pages here

**Comment by anxolerd** [comment]
@webknjaz Provide more info or tag someone who can.

**Comment by webknjaz** [comment]
It's all about to typical website pages like Abuse, Terms of use, Disclaimer etc.

**Comment by webknjaz** [comment]
@gora050 you may take this one.

**Comment by anxolerd** [comment]
[2016-01-27 22:38 EET] Updated issue description. @webknjaz please, check if everything is correct there.

**Comment by webknjaz** [comment]
@anxolerd texts should be crowdsourced, I think nobody can help us with this.
Perhaps we could do this all together.

//cc: @bluebirrd
