### ISSUE TITLE
API and node.js

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#4]
synchronize an API behavior with https://github.com/GDG-Ukraine/gdgregform

API endpoints list:
* [x] `GET /api/info`
* [x] `GET /api/places`
* [x] `GET /api/events/:id`
* [x] `POST /api/events/` <- [here](https://github.com/GDG-Ukraine/gdgregform/blob/master/server/api/gevents.js#L64) it is `/api/events` (w/o trailing slash)
* [x] `PUT /api/events/:id`
* [x] `DELETE /api/events/:id`
* [x] `GET /api/events`
* [x] `POST /api/events/:id/approve`
* [x] `POST /api/events/:id/send-confirm`
* [x] `POST /api/events/:id/resend`
* [x] `POST /api/events/:id/delete`
* [X] `POST /api/events/:id/invites` #76 fed90ad091c8e7c5ade6c0f8ae1c22e1a5b3058f
* [x] `POST /api/events/:id/report` #75 1444198b4ca0892a95b33427902fb502031accb0
* [x] `GET /api/participants`
* [x] `POST /api/participants` <- found it [here](https://github.com/GDG-Ukraine/gdgregform/blob/master/server/api/participants.js#L37)
* [x] `GET /api/participants/:id` (TODO: find_events_by_user)
* [x] `PUT /api/participants/:id` (TODO: find_events_by_user)
 <- found it [here](https://github.com/GDG-Ukraine/gdgregform/blob/master/server/api/participants.js#L61)
* [x] `GET /card/:id`
* [x] `GET /confirm/:id`
* [x] `GET /auth`

There is also login page at '/' <- look [here](https://github.com/GDG-Ukraine/gdgregform/blob/master/server/app.js#L56)
Other tasks:
* [X] Auth check at corresponding endpoints #46 64b0cd4
* [x] OAuth2 #6
* [X] Angular adjustments #71 fd6a50b25a5c397affa3a7cb0f6ae5047c0e6995

Additional blockers:
* [X] OAuth2 token auto-refresh strategy #70 a46f4c1b9a13b921e2250d4ada5e4cff26371425

**Comment by webknjaz** [comment]
// in progress. see `api-for-admin` and `auth` branches

**Comment by webknjaz** [comment]
@anxolerd please help me check whether I forgot anything and add missing points to the list.

**Comment by anxolerd** [comment]
@webknjaz I've added all points I found to not appear in your list to the task description.

**Comment by webknjaz** [comment]
@anxolerd Basic points are all fulfilled. Let's merge #77
