### ISSUE TITLE
Google OAuth2

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#6]
Check some Google OAuth2 package, enable and bind to the /auth handler.
https://developers.google.com/identity/protocols/OAuth2WebServer
https://developers.google.com/api-client-library/python/
https://pypi.python.org/pypi/google-api-python-client
- [X] CherryPy plugin bf9a98bb6d936b13e0b6728ba80435fad2440ee1
- [X] Admin auth similar to existing one `auth` branch
- [X] Secure api endpoints #46 64b0cd487d5be2e465a44cc3ceeabea550009f64
- [X] Accessible Google API #5

``` python
    # import the interface for publishing `cherrypy.engine` to channels:
    from GDGUkraine.lib.utils.signals import pub
    ...
    # get the API instance:
    api = pub('google-api')
    ...
    # run whatever query you want against GoogleAPI:
    api.get('https://www.googleapis.com/oauth2/v1/userinfo').json()
```
- [ ] Migrate regform front-end to Google Identity Platform #79 
- [x] Back-end auth of event participants if they click G+ Sign-In button #40
- [X] Auto-refresh token strategy #70 a46f4c1b9a13b921e2250d4ada5e4cff26371425
